# Numpy

### Import numpy

In [ ]:
import numpy as np

### Creating arrays from Python lists

In [3]:

list1 = [1, 2, 3, 4, 5]
arr1 = np.array(list1)
print(f"From list: {arr1}")

From list: [1 2 3 4 5]


### Creating arrays with a specific range

In [4]:
arr_range = np.arange(10) # 0 to 9
print(f"Using arange(10): {arr_range}")

Using arange(10): [0 1 2 3 4 5 6 7 8 9]


### Creating arrays with zeros, ones, or an empty shell

In [5]:
zeros_arr = np.zeros((2, 3)) # 2 rows, 3 columns of zeros
ones_arr = np.ones(4)      # 1D array of four ones
empty_arr = np.empty((3, 2)) # 3 rows, 2 columns (uninitialized values)
print(f"Zeros array (2x3):\n{zeros_arr}")
print(f"Ones array (1D):\n{ones_arr}")
print(f"Empty array (3x2, values may vary):\n{empty_arr}")

Zeros array (2x3):
[[0. 0. 0.]
 [0. 0. 0.]]
Ones array (1D):
[1. 1. 1. 1.]
Empty array (3x2, values may vary):
[[0. 0.]
 [0. 0.]
 [0. 0.]]


### Creating an identity matrix (square matrix with ones on the diagonal)

In [6]:
identity_matrix = np.eye(3)
print(f"Identity matrix (3x3):\n{identity_matrix}")

Identity matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Creating arrays with evenly spaced values within a range

In [8]:

linspace_arr = np.linspace(0, 10, 5) # 5 evenly spaced points between 0 and 10
print(f"Linspace (0 to 10, 5 points): {linspace_arr}")

print("Array Attributes")
print("--------------------")
print(f"Array: {arr1}")
print(f"Shape of arr1: {arr1.shape}") # Dimensions of the array
print(f"Data type of arr1: {arr1.dtype}") # Type of elements in the array
print(f"Number of dimensions of arr1: {arr1.ndim}") # Number of dimensions (axes)
print(f"Number of elements in arr1: {arr1.size}") # Total number of elements

multi_dim_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\nMulti-dimensional array:\n{multi_dim_arr}")
print(f"Shape of multi_dim_arr: {multi_dim_arr.shape}")
print(f"Number of dimensions of multi_dim_arr: {multi_dim_arr.ndim}")

print("Array Operations (Element-wise)")
print("---------------------------------")
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])
print(f"Array A: {arr_a}")
print(f"Array B: {arr_b}")

print(f"Addition (A + B): {arr_a + arr_b}")
print(f"Subtraction (A - B): {arr_a - arr_b}")
print(f"Multiplication (A * B): {arr_a * arr_b}")
print(f"Division (A / B): {arr_a / arr_b}")
print(f"Exponentiation (A ** 2): {arr_a ** 2}")

Linspace (0 to 10, 5 points): [ 0.   2.5  5.   7.5 10. ]
Array Attributes
--------------------
Array: [1 2 3 4 5]
Shape of arr1: (5,)
Data type of arr1: int32
Number of dimensions of arr1: 1
Number of elements in arr1: 5

Multi-dimensional array:
[[1 2 3]
 [4 5 6]]
Shape of multi_dim_arr: (2, 3)
Number of dimensions of multi_dim_arr: 2
Array Operations (Element-wise)
---------------------------------
Array A: [1 2 3]
Array B: [4 5 6]
Addition (A + B): [5 7 9]
Subtraction (A - B): [-3 -3 -3]
Multiplication (A * B): [ 4 10 18]
Division (A / B): [0.25 0.4  0.5 ]
Exponentiation (A ** 2): [1 4 9]


### Universal functions (ufuncs)

In [11]:
print(f"Square root of A: {np.sqrt(arr_a)}")
print(f"Sine of A: {np.sin(arr_a)}")

Square root of A: [1.         1.41421356 1.73205081]
Sine of A: [0.84147098 0.90929743 0.14112001]


In [12]:
print("Array Indexing and Slicing")
print("------------------------------")
arr_slice = np.arange(10, 20) # Array from 10 to 19
print(f"Original array for slicing: {arr_slice}")
print(f"Element at index 0: {arr_slice[0]}")
print(f"Elements from index 2 to 5 (exclusive): {arr_slice[2:6]}")
print(f"Elements from index 5 to end: {arr_slice[5:]}")
print(f"Elements from beginning to index 3 (exclusive): {arr_slice[:4]}")
print(f"Last element: {arr_slice[-1]}")

multi_dim_slice = np.array([[10, 11, 12], [20, 21, 22], [30, 31, 32]])
print(f"Multi-dimensional array for slicing:\n{multi_dim_slice}")
print(f"Element at [0, 1]: {multi_dim_slice[0, 1]}") # First row, second column
print(f"First row: {multi_dim_slice[0, :]}")
print(f"Second column: {multi_dim_slice[:, 1]}")
print(f"Sub-array (first 2 rows, last 2 columns):\n{multi_dim_slice[:2, 1:]}")

Array Indexing and Slicing
------------------------------
Original array for slicing: [10 11 12 13 14 15 16 17 18 19]
Element at index 0: 10
Elements from index 2 to 5 (exclusive): [12 13 14 15]
Elements from index 5 to end: [15 16 17 18 19]
Elements from beginning to index 3 (exclusive): [10 11 12 13]
Last element: 19
Multi-dimensional array for slicing:
[[10 11 12]
 [20 21 22]
 [30 31 32]]
Element at [0, 1]: 11
First row: [10 11 12]
Second column: [11 21 31]
Sub-array (first 2 rows, last 2 columns):
[[11 12]
 [21 22]]


In [13]:
print("Reshaping and Transposing")
print("----------------------------")
arr_reshape = np.arange(12)
print(f"Original 1D array: {arr_reshape}")
reshaped_arr = arr_reshape.reshape(3, 4) # Reshape into 3 rows, 4 columns
print(f"Reshaped to 3x4:\n{reshaped_arr}")

transposed_arr = reshaped_arr.T # Transpose (rows become columns and vice versa)
print(f"Transposed array:\n{transposed_arr}")

Reshaping and Transposing
----------------------------
Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transposed array:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [14]:
print("Aggregation Functions")
print("-------------------------")
agg_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Array for aggregation:\n{agg_arr}")
print(f"Sum of all elements: {np.sum(agg_arr)}")
print(f"Minimum of all elements: {np.min(agg_arr)}")
print(f"Maximum of all elements: {np.max(agg_arr)}")
print(f"Mean of all elements: {np.mean(agg_arr)}")
print(f"Standard deviation of all elements: {np.std(agg_arr)}")

print(f"Sum along columns (axis=0): {np.sum(agg_arr, axis=0)}") # Sum down each column
print(f"Sum along rows (axis=1): {np.sum(agg_arr, axis=1)}")    # Sum across each row

Aggregation Functions
-------------------------
Array for aggregation:
[[1 2 3]
 [4 5 6]]
Sum of all elements: 21
Minimum of all elements: 1
Maximum of all elements: 6
Mean of all elements: 3.5
Standard deviation of all elements: 1.707825127659933
Sum along columns (axis=0): [5 7 9]
Sum along rows (axis=1): [ 6 15]


In [15]:
print("Stacking and Splitting Arrays")
print("---------------------------------")
stack_arr1 = np.array([1, 2, 3])
stack_arr2 = np.array([4, 5, 6])
print(f"Array 1: {stack_arr1}")
print(f"Array 2: {stack_arr2}")

v_stack = np.vstack((stack_arr1, stack_arr2)) # Stack vertically (adds rows)
h_stack = np.hstack((stack_arr1, stack_arr2)) # Stack horizontally (concatenates)
print(f"Vertically stacked:\n{v_stack}")
print(f"Horizontally stacked: {h_stack}")

Stacking and Splitting Arrays
---------------------------------
Array 1: [1 2 3]
Array 2: [4 5 6]
Vertically stacked:
[[1 2 3]
 [4 5 6]]
Horizontally stacked: [1 2 3 4 5 6]


### Splitting arrays

In [17]:
arr_to_split = np.arange(9).reshape(3, 3)
print(f"\nArray to split:\n{arr_to_split}")
h_split = np.hsplit(arr_to_split, 3) # Split horizontally into 3 equal parts
v_split = np.vsplit(arr_to_split, 3) # Split vertically into 3 equal parts
print(f"Horizontal split (list of arrays): {h_split}")
print(f"Vertical split (list of arrays): {v_split}")


Array to split:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Horizontal split (list of arrays): [array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]
Vertical split (list of arrays): [array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
